version: '3'
services:
  flask-app:
    build: ./codeLlama/
    container_name: my_cuda_app
    ports:
      - "80:5000"
    network_mode: host
    environment:
      - CODEMODEL=CodeLlama-7b-Python
    volumes:
      - ./codeLlama/CodeLlama-7b-Python:/app/codeLlama/CodeLlama-7b-Python
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
